language: ruby
script: "rake spec && rake cucumber"
rvm: 1.9.2
services: mongodb
notifications:
  email:
    - tobias.pfeiffer@student.hpi.uni-potsdam.de
    - james+travis-ci-broken@jamesrgifford.com
    - kh@kalonhinds.com
  irc: "irc.freenode.org#hacketyhack"

